RNS_DOWNLOAD_FILE = "gamemodes/SuperS/supers.data"

-- Item Types
SUPERS_ITEM_TYPE_BOOST = 1
SUPERS_ITEM_TYPE_JUMP = 2
SUPERS_ITEM_TYPE_REPAIR = 3
SUPERS_ITEM_TYPE_ROCKET = 4
SUPERS_ITEM_TYPE_WEAPON = 5
